/* This file was generated by syncqt. */
#ifndef QT_QTWIDGETS_VERSION_H
#define QT_QTWIDGETS_VERSION_H

#define QTWIDGETS_VERSION_STR "5.15.7"

#define QTWIDGETS_VERSION 0x050F07

#endif // QT_QTWIDGETS_VERSION_H
