QT.dtkcore.VERSION = 5.6.12
QT.dtkcore.MAJOR_VERSION = 5
QT.dtkcore.MINOR_VERSION = 6
QT.dtkcore.PATCH_VERSION = 12
QT.dtkcore.name = dtkcore
QT.dtkcore.module = dtkcore
QT.dtkcore.tools = /runtime/libexec/dtk5/DCore/bin
QT.dtkcore.libs = /runtime/lib/x86_64-linux-gnu
QT.dtkcore.includes = /runtime/include/dtk5/DCore
QT.dtkcore.frameworks =
QT.dtkcore.depends = core dbus xml
QT.dtkcore.module_config = v2 ltcg
QT.dtkcore.DEFINES += QT_MESSAGELOGCONTEXT
QT_MODULES +=
